apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp-orders
  template:
    metadata:
      labels: 
        app: exp-orders
    spec:
      containers:
        - name: exp-orders
          image: anawatj/exp-orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: exam
            - name: MONGO_URI
              value: 'mongodb://exp-orders-mongo-srv:27017/orders'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: exp-orders-srv
spec:
  selector:
    app: exp-orders
  ports:
    - name: exp-orders
      protocol: TCP
      port: 3000
      targetPort: 3000