apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-books-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp-books
  template:
    metadata:
      labels: 
        app: exp-books
    spec:
      containers:
        - name: exp-books
          image: anawatj/exp-books
          env:
            - name: MONGO_URI
              value: 'mongodb://exp-books-mongo-srv:27017/books'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: exp-books-srv
spec:
  selector:
    app: exp-books
  ports:
    - name: exp-books
      protocol: TCP
      port: 3000
      targetPort: 3000