apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp-auth
  template:
    metadata:
      labels: 
        app: exp-auth
    spec:
      containers:
        - name: exp-auth
          image: anawatj/exp-auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: exp-auth-srv
spec:
  selector:
    app: exp-auth
  ports:
    - name: exp-auth
      protocol: TCP
      port: 3000
      targetPort: 3000